---
- hosts: pg_replica
  gather_facts: True
  become: True

  roles:
  - my-postgres
  
  vars:
    init_schema_slave: False

  tasks:
  - name: Dump cluster shema
    shell: sudo -u postgres pg_dumpall --schema-only > /tmp/pg_shema_slave.sql
    delegate_to: pg-master-test
    run_once: True

  - name: Copy dump to localhost
    fetch:
      src: /tmp/pg_shema_slave.sql
      dest: /tmp/pg_shema_slave.sql
      flat: True
    delegate_to: pg-master-test
    run_once: True

  - name: Send dump to replica
    copy:
      src: /tmp/pg_shema_slave.sql
      dest: /tmp/pg_shema_slave.sql
  
  - name: Restore postgres shema
    shell: psql < /tmp/pg_shema_slave.sql
    become_user: postgres